fix plot style breakage
r3235 moved plot styles to graph.style. As a result, plotitem raises

AttributeError: 'module' object has no attribute 'getdefaultprovider'

because style.getdefaultprovider() does not find getdefaultprovider when
called in the module style (graph.style).

Fix this by referencing getdefaultprovider() directly (without the
module) in that module.